name: GrandMaster SEC | 09:30→09:30 Boundary Scan (Self-Healing)
on:
  workflow_dispatch:
  schedule:
    - cron: "35 13 * * 1-5"
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Grand Master SEC v23.2M
        env: { CI: "true" }
        run: python -u -m scripts.sec.grandmaster_sec_v23
