name: SEC Filings Only — Step 6

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"   # runs daily at 14:00 UTC (09:00 ET)

jobs:
  sec_only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas lxml beautifulsoup4

      - name: Run SEC-only fetch
        run: |
          mkdir -p data
          python sec_only.py

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/sec_filings_snapshot.json data/sec_filings_snapshot.csv || true
          git commit -m "Update SEC filings snapshot [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF##*/}
