name: SEC Filings Only — Step 6

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5"  # 9:00 UTC (~4am ET) weekdays

jobs:
  sec_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run SEC-only fetch
        env:
          SEC_USER_AGENT: ${{ secrets.FETCH_UA }}
          MAX_PAGES: "24"
          COUNT_PER_PAGE: "100"
        run: |
          mkdir -p data
          python sec_only.py
          ls -lh data

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sec_only_outputs
          path: |
            data/sec_filings_snapshot.json
            data/sec_filings_snapshot.csv

      - name: Deploy to Hostinger via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: "data/sec_filings_snapshot.*"
          remote_path: ${{ secrets.SFTP_DIR }}
          sftp_only: true
          delete: false
